#ifndef _CC2500_H_
#define _CC2500_H_

#include "spi_protocol.h"


/*	Protocol to send data and stuff */

/*	Values */

#define SETTING_IOCFG0 0x06
#define SETTING_MCSM1 0x3C
#define SETTING_MCSM0 0x18
#define SETTING_PKTLEN 0X13
#define SETTING_PKTCTRL0 0x05

#define SMARTRF_SETTING_FSCTRL1 0x07
#define SMARTRF_SETTING_FSCTRL0 0x00
#define SMARTRF_SETTING_FREQ2 0x5D
#define SMARTRF_SETTING_FREQ1 0x44
#define SMARTRF_SETTING_FREQ0 0xEC
#define SMARTRF_SETTING_MDMCFG4 0x2D
#define SMARTRF_SETTING_MDMCFG3 0x3B
#define SMARTRF_SETTING_MDMCFG2 0x73
#define SMARTRF_SETTING_MDMCFG1 0x23
#define SMARTRF_SETTING_MDMCFG0 0x3B
#define SMARTRF_SETTING_CHANNR 0x06
#define SMARTRF_SETTING_DEVIATN 0x01
#define SMARTRF_SETTING_FREND1 0xB6
#define SMARTRF_SETTING_FREND0 0x10
#define SMARTRF_SETTING_MCSM0 0x18
#define SMARTRF_SETTING_FOCCFG 0x1D
#define SMARTRF_SETTING_BSCFG 0x1C
#define SMARTRF_SETTING_AGCCTRL2 0xC7
#define SMARTRF_SETTING_AGCCTRL1 0x00
#define SMARTRF_SETTING_AGCCTRL0 0xB0
#define SMARTRF_SETTING_FSCAL3 0xEA
#define SMARTRF_SETTING_FSCAL2 0x0A
#define SMARTRF_SETTING_FSCAL1 0x00
#define SMARTRF_SETTING_FSCAL0 0x11
#define SMARTRF_SETTING_FSTEST 0x59
#define SMARTRF_SETTING_TEST2 0x88
#define SMARTRF_SETTING_TEST1 0x31
#define SMARTRF_SETTING_TEST0 0x0B
#define SMARTRF_SETTING_FIFOTHR 0x07
#define SMARTRF_SETTING_IOCFG2 0x29
#define SMARTRF_SETTING_PKTCTRL1 0x04
#define SMARTRF_SETTING_PKTCTRL0 0x05
#define SMARTRF_SETTING_ADDR 0x00

/*	Addresses */

#define SETTING_A_IOCFG0 0x02
#define SETTING_A_MCSM1 0x17
#define SETTING_A_MCSM0 0x18
#define SETTING_A_PKTLEN 0x06
#define SETTING_A_PKTCTRL0 0x08

#define SMARTRF_SETTING_A_FSCTRL1 0x0B
#define SMARTRF_SETTING_A_FSCTRL0 0x0C
#define SMARTRF_SETTING_A_FREQ2 0x0D
#define SMARTRF_SETTING_A_FREQ1 0x0E
#define SMARTRF_SETTING_A_FREQ0 0x0F
#define SMARTRF_SETTING_A_MDMCFG4 0x10
#define SMARTRF_SETTING_A_MDMCFG3 0x11
#define SMARTRF_SETTING_A_MDMCFG2 0x12
#define SMARTRF_SETTING_A_MDMCFG1 0x13
#define SMARTRF_SETTING_A_MDMCFG0 0x14
#define SMARTRF_SETTING_A_CHANNR 0x0A
#define SMARTRF_SETTING_A_DEVIATN 0x15
#define SMARTRF_SETTING_A_FREND1 0x21
#define SMARTRF_SETTING_A_FREND0 0x22
#define SMARTRF_SETTING_A_MCSM0 0x18
#define SMARTRF_SETTING_A_FOCCFG 0x19
#define SMARTRF_SETTING_A_BSCFG 0x1A
#define SMARTRF_SETTING_A_AGCCTRL2 0x1B
#define SMARTRF_SETTING_A_AGCCTRL1 0x1C
#define SMARTRF_SETTING_A_AGCCTRL0 0x1D
#define SMARTRF_SETTING_A_FSCAL3 0x23
#define SMARTRF_SETTING_A_FSCAL2 0x24
#define SMARTRF_SETTING_A_FSCAL1 0x25
#define SMARTRF_SETTING_A_FSCAL0 0x26
#define SMARTRF_SETTING_A_FSTEST 0x29
#define SMARTRF_SETTING_A_TEST2 0x2C
#define SMARTRF_SETTING_A_TEST1 0x2D
#define SMARTRF_SETTING_A_TEST0 0x2E
#define SMARTRF_SETTING_A_FIFOTHR 0x03
#define SMARTRF_SETTING_A_IOCFG2 0x00
#define SMARTRF_SETTING_A_PKTCTRL1 0x07
#define SMARTRF_SETTING_A_PKTCTRL0 0x08
#define SMARTRF_SETTING_A_ADDR 0x09

/* Commands */

#define RF_COMMAND_RESET 0x30
#define RF_COMMAND_SFSTXON 0x31
#define RF_COMMAND_SXOFF 0x32
#define RF_COMMAND_SCAL 0x33
#define RF_COMMAND_SRX 0x34
#define RF_COMMAND_STX 0x35
#define RF_COMMAND_SIDLE 0x36
#define RF_COMMAND_SWOR 0x38
#define RF_COMMAND_SPWD 0x39
#define RF_COMMAND_SFRX 0x3A
#define RF_COMMAND_SFTX 0x3B
#define RF_COMMAND_SWORRST 0x3C
#define RF_COMMAND_SNOP 0x3D

void RF_Config(void);
void RF_Verify_Config(uint16_t* buffer);
void RF_Reset(void); 
void RF_SetToRXMode(void); 
void RF_SetToTXMode(void);	
void RF_FlushRXMode(void); 
void RF_FlushTXMode(void);
void RF_SetToIdleMode(void); 							 
uint16_t RF_GetChipStatus(void); 
void RF_Transmit(uint16_t* data); 
void RF_Receive(uint16_t* data);


#endif
